export const FETCH_SUPERHERO_REQUEST = "FETCH_SUPERHERO_REQUEST";
export const FETCH_SUPERHERO_SUCCESS = "FETCH_SUPERHERO_SUCCESS";
export const FETCH_SUPERHERO_FAILURE = "FETCH_SUPERHERO_FAILURE";
export const SET_EXPECTED_SUPERHEROS = "SET_EXPECTED_SUPERHEROS";
export const ADD_N_SUPERHEROES = "ADD_N_SUPERHEROES";
